### ISSUE TITLE
Projects with ≥ 2 executables called "main" make dune-deps fail

### ISSUE THREAD

**Issue by smondet** [mjambon/dune-deps#1]
I hit the exception there: https://github.com/mjambon/dune-deps/blob/master/src/Graph.ml#L67

**Comment by mjambon** [comment]
Thanks for the report. Working on it!

**Comment by mjambon** [comment]
I'm not sure what name to show these executables as, i.e. which labels to show on the nodes in the graph rendering. Here are some options:

1. Use the original name specified in the dune file such as `main`. This results in several nodes with the same label.
2. Use the full path to the folder containing the dune file as a label such as `src/foo/test/main`. This may be too noisy/ugly in general.
3. Assign them numeric identifiers such as `main/1` and `main/2`. This isn't useful without knowing which is which.
4. Something more advanced, like guessing a good name, somehow.

I'll start with (1).

**Comment by smondet** [comment]
If you need inspiration there are the various methods defined by Emacs to uniquify buffer names: cf. variable `uniquify-buffer-name-style` :)

Option 2. would still be useful I think to inspect large codebases (even if a bit ugly).

**Comment by mjambon** [comment]
I pushed changes that allow multiple executables to have the same name. So you should see several `main` nodes in the graph.

**Comment by mjambon** [comment]
The emacs way should work reasonably well. I was originally thinking of using the following format:

```
**/foo/bin/main
**/bar/bin/main
```
but maybe the default emacs style is just fine:
```
main<foo/bin>
main<bar/bin>
```

**Comment by mjambon** [comment]
I implemented executable name disambiguation like emacs does for its file buffers. Should be better now!
