### ISSUE TITLE
Wish: support `subdir` stanzas

### ISSUE THREAD

**Issue by jberdine** [mjambon/dune-deps#20]
It would be nice if dune-deps would support dune's `subdir` stanzas. Briefly, treat `(subdir foo <contents>)` just as if there was a `dune` file containing `<contents>` in the `foo` dir.

**Comment by mjambon** [comment]
This sounds like a good thing to add.

**Comment by mjambon** [comment]
Do you know by any chance a public repo which uses this feature? (to be used as a test target)

**Comment by jberdine** [comment]
I don't make any claim that it is a good test, but there is https://github.com/facebook/infer/blob/master/sledge/dune

**Comment by mjambon** [comment]
Great, thanks!

**Comment by mjambon** [comment]
Check out the output for infer/sledge at #21!
