### ISSUE TITLE
Is it possible to try the sample code on macOS?

### ISSUE THREAD

**Issue by diohabara** [mjambon/dune-deps#22]
I think `tred` is not included in macOS and cannot be installed by `brew`. That's why the example command may not work on macOS.

```bash
$ dune-deps | tred | dot -Tpng > deps.png
```

If there were another sample program that works in macOS, it is more helpful to write it in README.
If I was wrong, it helps me to teach how it works. Thanks!

**Comment by mjambon** [comment]
`tred` and `dot` are from the graphviz suite of tools. Did you try `brew install graphviz`? I can't see by just looking at the [brew formula](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/graphviz.rb) if that would work. Hopefully :-)

**Comment by diohabara** [comment]
Thank you! It works pretty well!
