### ISSUE TITLE
Only show / expand given list of libraries

### ISSUE THREAD

**Issue by rbardou** [mjambon/dune-deps#5]
Nice tool! I wanted to do that for a while :)

I just tried it on the Tezos codebase (on the `src` directory) and the result is a bit messy. I think it could be made more readable if we had the possibility to restrict the graph to a list of binaries and libraries.

The Tezos codebase contains a large amount of libraries and executables, all in subdirectories of the `src` directory. If I run `dune-deps src`, I get everything. With `tred` it is much more bearable but still messy. If I run `dune-deps src/bin_node`, I only get the node (in particular internal libraries are no longer expanded), which is not very informative.

So I suggest giving the possibility to give the list of dune files on the command-line. This would give more control over what exactly is show in the graph (I could give the dune files of several subdirectories of `src`, but not the ones I don't care about) and what is expanded (I could give the dune file of an internal library if I want to see what it depends on, and I could not give it if I want to see it as a blackbox).

Thanks again for your work!

**Comment by mjambon** [comment]
I looked at the tools listed on the Graphviz site. I haven't found something that would do what we want and that's also easy to use.

I think we want the following flow:

1. Run dune-deps naively and see there's too much stuff.
2. Identify the labels for the nodes of interest.
3. Run dune-deps in filtering mode, which would remove all nodes that are not on a path from or to a node of interest.

Maybe more filtering would be needed. We have to try.

**Comment by ygrek** [comment]
Another possible angle / feature request - exclude all external libraries, show only the ones from dune project

**Comment by mjambon** [comment]
@ygrek sounds reasonable. I'm creating a separate issue for this.

**Comment by mjambon** [comment]
I added options to:

* exclude executables
* exclude external libraries
* show only dependencies or reverse dependencies of selected libraries

... and I'm pretty happy with the results. It's in `master`. I'm aiming for a release tomorrow.

**Comment by rbardou** [comment]
FYI, I just ran (in the root directory of Tezos):
```
dune-deps src -h tezos-node | tred > deps.dot && dot -Tpng deps.dot -o deps.png
```
And the result is much more readable! Thank you for your work :)

![deps](https://user-images.githubusercontent.com/4598821/79224941-3cc73280-7e5c-11ea-83ae-cb97669400b8.png)
